[package]
name = "ptest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goose = "0.16.3"
tokio = { version = "1", features = ["full"] }
goose-eggs = "0.4"
serde_json = "1.0"
reqwest = "0.11.11"